module.exports = {
  printWidth: 100,
  tabWidth: 2,
  semi: true,
  vueIndentScriptAndStyle: true,
  singleQuote: false,
  quoteProps: "as-needed",
  bracketSpacing: true,
  jsxBracketSameLine: false,
  jsxSingleQuote: false,
  arrowParens: "always",
  insertPragma: false,
  requirePragma: false,
  proseWrap: "never",
  htmlWhitespaceSensitivity: "strict",
  endOfLine: "auto",
  rangeStart: 0,
};
